version: '3.8'

services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - network_monitor

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network_monitor

volumes:
  postgres_data:

networks:
  network_monitor:
    driver: bridge 